Creation of Flask App
jwyatt1999/CITS3403_Cartographers pull request #15
Opened 2022-03-27 14:08 UTC by Bsubs

Created the skeleton structure with a consistent theme with a navbar which allows for easy access to all pages with a shallow tree structure. Also implemented the homepage with large buttons as discussed in the meeting.

2022-03-28 13:33 UTC, jwyatt1999 requested changes
I think the changes look fine. The skeleton pages will definitely need some attention but we will get to that at some point and these are fine starting points. Just had a few queries regarding some commented css. 

Also, we aren't able to merge your PR just yet because there is a merge conflict (I pulled from main and you pulled from main, I then edited styles.css in my PR and have merged my PR, and you've made some changes to styles.css in your PR so github doesn't know what the original styles.css should be changed to). This can be resolved by a merge conflict resolution program after pulling in my commits to your branch, though I don't know if VSCode naturally has one (it certainly could) - I would err on the side of caution and resolve the merge conflict in github by clicking the 'Web Editor' button at the bottom of the PR near where it says 'Resolve conflicts'. I can help you with this if you'd like, it looks like we just need to add the two files together since we don't have any common id's/classes we are both applying styles to :)

2022-03-28 13:33 UTC, jwyatt1999 commented on style.css
> +} */
Is this meant to be removed?

2022-03-28 13:33 UTC, jwyatt1999 commented on style.css
> +} */
Is this also meant to be removed?

2022-03-28 13:38 UTC, jwyatt1999 commented
Also, have you run the main page and styles.css through the HTML and CSS validator?

2022-04-10 05:41 UTC, jwyatt1999 reviewed
Just found a comment that should probably be removed. I'll be happy to approve this once the css file (...\static\style.css) and html files (all of those in ...\templates) have been run through the validator

2022-04-10 05:41 UTC, jwyatt1999 commented on cartographers/static/style.css
> +/* CSS for Background */
Has this page been put through the CSS validator?

2022-04-10 05:41 UTC, jwyatt1999 commented on cartographers/templates/game_page.html
> +                </tr> -->
This commented section should be deleted

2022-04-16 04:01 UTC, Bsubs commented on cartographers/templates/game_page.html
> +                </tr> -->
Removed the unecessary comment

2022-04-16 04:02 UTC, jwyatt1999 commented
This looks good to me!

2022-04-16 04:13 UTC, jwyatt1999 approved these changes

2022-04-16 04:19 UTC, merged